### ISSUE TITLE
📃: add hello world in rexx

### ISSUE THREAD

**Issue by simran0963** [abhisek247767/Hello-World#111]
🟢 Title : add hello world program in rexx programming language
🟢 Programming language : REXX
🟢 Objective : adding hello world in a different programming language than other hello world commits
🟢 Summary : REXX (Restructured Extended Executor) is a versatile, high-level programming language developed by IBM's Mike Cowlishaw1. It's designed to be easy to learn and read, making it a great choice for scripting, macro languages, and application development1

Hey please add the hacktoberfest2024 and hacktoberfest-accepted labels when merging

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Simran

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey😍. 
Enjoy! 😎

**Comment by abhisek247767** [comment]
Assigned
