### ISSUE TITLE
Hello world program in swift and lua

### ISSUE THREAD

**Issue by Cgarg9** [abhisek247767/Hello-World#13]
I would like to contribute to this project by writing hello world program in swift and lua. Please assign me this issue

**Comment by abhisek247767** [comment]
first please check the guidelines properly. And assigned you for this issue.

**Comment by Cgarg9** [comment]
Hi. You have closed the issue. Kindly re-open this. I would like to add hello world code in swift

**Comment by abhisek247767** [comment]
Done @Cgarg9 . Go ahead

**Comment by Cgarg9** [comment]
Hi @abhisek247767 why have you closed it again? Please give me till EOD to raise a PR.

**Comment by abhisek247767** [comment]
No worry.. you raised PR
