### ISSUE TITLE
Add hello world 

### ISSUE THREAD

**Issue by bhaviya18** [abhisek247767/Hello-World#35]
I would like to add hello world in kotlin.

**Comment by bhaviya18** [comment]
@abhisek247767  It is not available. Kindly assign me this task.

**Comment by abhisek247767** [comment]
Done.

**Comment by bhaviya18** [comment]
@abhisek247767 I didnt create a pull request yet. Issue is closed by you.

**Comment by bhaviya18** [comment]
Thank you!
