### ISSUE TITLE
📃: Hello World in Kotlin

### ISSUE THREAD

**Issue by AkshitSalwan** [abhisek247767/Hello-World#99]
🟢 Title :Hello World
🟢 Programming language : Kotlin
🟢 Objective :Beginner friendly code snippet
🟢 Summary :just adding a basic kotlin code to print hello world

***********************************************************************

✅ Details to Include When Taking the Issue:
Name :Hacktoberfest ,hacktoberfest-accepted 

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey😍. 
Enjoy! 😎

**Comment by AkshitSalwan** [comment]
Done buddy, also a request from my side to add hacktoberfest and hacktoberfest-accepted labels.

**Comment by abhisek247767** [comment]
Kotlin already available
